app = "home-finder"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile.fly"

[mounts]
  source = "home_finder_data"
  destination = "/app/data"

[env]
  MALLOC_ARENA_MAX = "2"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
